version: '3.7'

networks:
  docker-php8-network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: always
    tty: true
    container_name: docker-php8-php
    networks:
      - docker-php8-network
    ports:
      - '9000:9000'
    volumes:
      - .:/home/app

  #  replace apache with nginx
  apache:
    build: ./docker/apache
    container_name: docker-php8-apache
    restart: always
    tty: true
    depends_on:
      - php
  #   - mariadb      
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - .:/home/app
    networks:
      - docker-php8-network


  #  mariadb:
  #    image: mariadb
  #    tty: true
  #    restart: always
  #    container_name: docker-php8-mariadb
  #    networks:
  #      - docker-php8-network
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - './docker/mysql/config/mariadb.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/database:/var/lib/mysql'
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  #  mysql:
  #    image: mysql:8
  #    tty: true
  #    restart: always
  #    container_name: docker-php8-mysql
  #    networks:
  #      - docker-php8-network
  #    ports:
  #      - '3306:3306'
  #    volumes:
  #      - './docker/mysql/config/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro'
  #      - './docker/mysql/database:/var/lib/mysql'
  #    environment:
  #      - MYSQL_PASSWORD=root
  #      - MYSQL_ROOT_PASSWORD=root
  #      - MYSQL_DATABASE=development

  #  phpmyadmin:
  #    image: library/phpmyadmin
  #    container_name: docker-php8-phpmyadmin
  #    tty: true
  #    networks:
  #      - docker-php8-network
  #    depends_on:
  #      - mysql
  #      - mariadb
  #    environment:
  #      PMA_USER: root
  #      PMA_PASSWORD: root
  #      PMA_HOSTS: mysql,mariadb
  #      PMA_PORT: 3306
  #      PMA_ARBITRARY: 1
  #    ports:
  #      - '8080:80'

  #  postgres:
  #    image: library/postgres:13-alpine
  #    container_name: docker-php8-postgres
  #    tty: true
  #    restart: always
  #    networks:
  #      - docker-php8-network
  #    ports:
  #      - '5432:5432'
  #    volumes:
  #      - './docker/postgres:/var/lib/postgresql/data'
  #    environment:
  #      - POSTGRES_USER=root
  #      - POSTGRES_PASSWORD=root
  #      - POSTGRES_DB=development

  #  redis:
  #    image: bitnami/redis:latest
  #    restart: always
  #    tty: true
  #    container_name: docker-php8-redis
  #    volumes:
  #      - ./docker/redis:/bitnami/redis/data
  #    networks:
  #      - docker-php8-network
  #    environment:
  #      - ALLOW_EMPTY_PASSWORD=no
  #      - REDIS_PASSWORD=root
  #    ports:
  #      - '6379:6379'
